[package]
name = "smoller"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.17"
libc = "0.2.106"
pin-project-lite = "0.2.7"
polling = "2.1.0"
socket2 = "0.4.2"
bytes = "0.4"
httparse = "1.1.2"
log = "0.3.6"
time = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
